### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by nrob81** [markusfisch/BarcodeScannerView#1]
Hello, 
thank you for this project!

i tried to use it in my app but i got only a blank screen instead of the camera view. 
can you please help me out? 

```kotlin
import android.Manifest
import android.content.pm.PackageManager
import android.hardware.camera2.CameraManager
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.view.WindowManager
import android.widget.TextView
import android.widget.Toast
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import de.markusfisch.android.barcodescannerview.widget.BarcodeScannerView

private const val TAG = "barcodescanner"
private const val REQUEST_CAMERA = 1

class ScanActivity : AppCompatActivity() {

    private lateinit var cameraListId: String
    private lateinit var textView: TextView
    private lateinit var scannerView: BarcodeScannerView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        window.addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
        checkPermission()
        setContentView(R.layout.activity_scan)

        val cameraManager = getSystemService(CAMERA_SERVICE) as CameraManager
        cameraListId = cameraManager.cameraIdList[0]

        textView = findViewById(R.id.text)
        textView.text = "textView.text"

        scannerView = findViewById(R.id.scanner_view)
        scannerView.cropRatio = .75f
        scannerView.setOnBarcodeListener {
            textView.post(Runnable {
                textView.text = it.text
            })
            true
        }
    }

    private fun checkPermission() {
        val permission = ContextCompat.checkSelfPermission(applicationContext, Manifest.permission.CAMERA)
        if (permission != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, arrayOf(Manifest.permission.CAMERA), REQUEST_CAMERA)
        }
    }

    private fun openCamera() {
        val cameraBack = cameraListId?.get(0)
        Log.i(TAG, "cameraBack = $cameraBack")

        val message = if (cameraBack != null) {
            scannerView.openAsync(BarcodeScannerView.findCameraId(cameraBack.code))
            "Cam opened"
        } else {
            "Can't get the id of back camera"
        }

        Toast.makeText(applicationContext, message, Toast.LENGTH_SHORT).show()
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == REQUEST_CAMERA) {
            val message = if (grantResults[0] == PackageManager.PERMISSION_GRANTED)  "granted" else "denied"
            Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
        }
    }

    override fun onResume() {
        super.onResume()
        openCamera()
    }


    override fun onPause() {
        super.onPause()
        scannerView.close()
    }
}
```

**Comment by markusfisch** [comment]
Hi, I think the problem is `BarcodeScannerView.findCameraId()`, which expects either [Camera.CameraInfo.FACING_BACK](https://developer.android.com/reference/android/hardware/Camera.CameraInfo#CAMERA_FACING_BACK) or [Camera.CameraInfo.FACING_FRONT](https://developer.android.com/reference/android/hardware/Camera.CameraInfo#CAMERA_FACING_FRONT).

So instead of:
```kotlin
scannerView.openAsync(BarcodeScannerView.findCameraId(cameraBack.code))
```
it should read:
```kotlin
scannerView.openAsync(BarcodeScannerView.findCameraId(Camera.CameraInfo.CAMERA_FACING_BACK));
```

`BarcodeScannerView.findCameraId()` is probably a bit misleading, but it comes from the underlying CameraView implementation [here](https://github.com/markusfisch/CameraView/blob/master/cameraview/src/main/java/de/markusfisch/android/cameraview/widget/CameraView.java#L62).

**Comment by nrob81** [comment]
@markusfisch thanks for the reply. i tried the Camera.CameraInfo.CAMERA_FACING_BACK but the ide complained about the deprecation of camera. Suggests using camera2 but i can't figure out, how.

**Comment by markusfisch** [comment]
Well, since BarcodeScannerView is a complete solution, including the camera part, there is no way to change the camera API. This is intentional, because BarcodeScannerView should simply provide a view that can scan a barcode, without having to worry about camera and barcode scanning.

To support older versions of Android, BarcodeScannerView is still using the legacy Camera API. This is fine as it is still supported even in the latest version of Android. At some point, probably not very far in the future, BarcodeScannerView will migrate to the new Camera API.

If you don't want to use BarcodeScannerView with the legacy Camera API - it's fine, I use this in all my projects to this date - you could use the Android [wrapper](https://github.com/zxing-cpp/zxing-cpp/tree/master/wrappers/android) of ZXing C++, the barcode scanning library, as a base for your application instead. It would be a bit more code, but not that much.

I also maintain a [fork](https://github.com/markusfisch/zxing-cpp/tree/master/wrappers/aar) of this wrapper that improves on a few things important to Android users, and that can be included via Maven.

**Comment by nrob81** [comment]
thank you, i am ok with the camera api. i'll try it out again.

**Comment by markusfisch** [comment]
Version 1.5.0 adds `openAsync()` without any parameters (see [this commit](https://github.com/markusfisch/BarcodeScannerView/commit/9bbd1759d7af909d712183f30b33334acadd35e8)), so you wouldn't have to worry about what Camera API the library is using.

Unfortunately, JitPack is [broken](https://github.com/jitpack/jitpack.io/issues/5866) at the moment, so you would have to include the aar [manually](https://github.com/markusfisch/BarcodeScannerView#manually). Sorry for this.
